version: "3.9"

services:
  plazasales-frontend:
    image: rahuljha1155/plaza-frontend:latest
    container_name: plazasales-frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - "./frontend/.env"
    networks:
      - plaza-network
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:3000/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  plaza-network:
    external: true
